testConnection/urls.py
from django.urls import path 

from . import views

app_name = 'testConnection'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),

]

testDB1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testConnection/', include('testConnection.urls')),
]

testConnection/models.py
from django.db import models
from django.utils import timezone

import datetime

# Create your models here.
'''
class Post(models.Model):
	title = models.CharField(max_length=100)
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
'''

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('publised date')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

    #must be seaprated with class Question 
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Publised recently?'



class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

testConnection/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

#from django.http import Http404

#from django.template import loader


#import from models
from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'testConnection/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		#return last 5 published questions
		return Question.objects.filter(
		    pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'testConnection/detail.html'
	def get_queryset(self):
	    return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'testConnection/results.html'



def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]

	'''import loader to use the following
	template = loader.get_template('testConnection/index.html')
	'''

	context = {
		'latest_question_list': latest_question_list,
	}
	#return HttpResponse(template.render(context, request))
	return render(request, 'testConnection/index.html', context)


def detail(request, question_id):
	''' Not using get_object_or_404 shortcut
	try:
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404('Question not exist')
	return render(request, 'testConnection/detail.html', {'question': question})
	'''
	#return HttpResponse("This is the question %s." %question_id)
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'testConnection/detail.html', {'question': question})


def results(request, question_id):
	'''
	response = "The result of question %s."
	return HttpResponse(response % question_id)
	'''
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'testConnection/results.html', {'question': question})

def vote(request, question_id):
	#return HttpResponse("Voting on question %s" %question_id)
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#redisplay the question voting form
		return render(request, 'testConnection/detail.html', {
			'question': question,
			'error_message': "Haven't select a choice",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		#always return an HttpResponseRedirect after successfully dealing with POST data
		return HttpResponseRedirect(reverse('testConnection:results', args=(question_id,)))

testConnection/templates/testConnection/detail.html
<h1> {{ question.question_text }} </h1>

{% if erro_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
{% endif %}

<form action="{% url 'testConnection:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
<br>
{% endfor %}
<input type="submit" value="Vote"/>
</form>

<!-- Display choices (before tut #4)
<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text}}</li>
	{% endfor %}
</ul>
-->

testConnection/templates/testConnection/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'testConnection/style.css' %}"  />

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'testConnection:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<p>No polls found</p>
	{% endif %}

testConnection/templates/testConnection/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>
			{{ choice.choice_text }} -- {{choice.votes}} vote{{choice.votes|pluralize}}
		</li>
		{% endfor %}
</ul>

<a href="{% url 'testConnection:detail' question.id %}">
	Vote again?
</a>